; PlatformIO Project Configuration File
;
; NOTA: Este archivo ahora maneja DOS placas (UNO y MEGA)
; y descarga automáticamente todas las librerías necesarias.

[platformio]
; Entorno por defecto al usar el botón genérico "Build"
default_envs = mega

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
; Filtro de compilación: Solo compila el código en esta carpeta
build_src_filter = +<controlador_uno/>
; Librerías para el UNO:
lib_deps = 
    arduino-libraries/Servo@1.2.1

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
build_src_filter = +<datalogger_mega/>
lib_deps = 
    adafruit/RTClib
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit BusIO
    electroniccats/MPU6050
    wollewald/INA226_WE
    arduino-libraries/SD