; platformio.ini (PARA EL PROYECTO DEL CONTROLADOR UNO)
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps = 
    arduino-libraries/Servo

; platformio.ini (PARA EL PROYECTO DEL DATALOGGER MEGA)
[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
lib_deps = 
    arduino-libraries/SD
    adafruit/RTClib
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit BusIO
    jrowberg/I2Cdevlib-Core
    jrowberg/MPU6050
    wollewald/INA226_WE